#ifndef __CPU_MAP_H
#define __CPU_MAP_H

// digital inputs
enum {
    DIGITAL_INPUT_1 = 1,
    DIGITAL_INPUT_2,
    DIGITAL_INPUT_3,
    DIGITAL_INPUT_4,
    DIGITAL_INPUT_5,
    DIGITAL_INPUT_6,
    DIGITAL_INPUT_7,
    DIGITAL_INPUT_8,
    DIGITAL_INPUT_9,
    DIGITAL_INPUT_10,
    DIGITAL_INPUT_11,
    DIGITAL_INPUT_12,
    DIGITAL_INPUT_13,
    DIGITAL_INPUT_14,
    DIGITAL_INPUT_15,
    DIGITAL_INPUT_16,
    DIGITAL_INPUT_MAX,
};

#define DIGITAL_INPUT_1_PIN  GPIO_PIN_0
#define DIGITAL_INPUT_1_PORT GPIOB

// digital outputs
enum {
    DIGITAL_OUTPUT_1 = 51,
    DIGITAL_OUTPUT_2,
    DIGITAL_OUTPUT_3,
    DIGITAL_OUTPUT_4,
    DIGITAL_OUTPUT_5,
    DIGITAL_OUTPUT_6,
    DIGITAL_OUTPUT_7,
    DIGITAL_OUTPUT_8,
    DIGITAL_OUTPUT_9,
    DIGITAL_OUTPUT_10,
    DIGITAL_OUTPUT_11,
    DIGITAL_OUTPUT_12,
    DIGITAL_OUTPUT_13,
    DIGITAL_OUTPUT_14,
    DIGITAL_OUTPUT_15,
    DIGITAL_OUTPUT_16,
    DIGITAL_OUTPUT_17,
    DIGITAL_OUTPUT_18,
    DIGITAL_OUTPUT_19,
    DIGITAL_OUTPUT_20,
    DIGITAL_OUTPUT_21,
    DIGITAL_OUTPUT_22,
    DIGITAL_OUTPUT_23,
    DIGITAL_OUTPUT_24,
    DIGITAL_OUTPUT_MAX,
};

#endif