#ifndef __ERROR_CODE_H
#define __ERROR_CODE_H

#define ERROR_CODE_FORMAT "ERR%d\n"

/* Error code */
// API error code
#define API_ERROR_CODE_FAIL_ALLOCATE_MEMORY_FOR_TOKEN 200
#define API_ERROR_CODE_INVALID_COMMAND_TYPE 201
#define API_ERROR_CODE_INVALID_COMMAND_ID 202
#define API_ERROR_CODE_INVALID_COMMAND_VARIANT 203
#define API_ERROR_CODE_INVALID_COMMAND_PARAMETER 204
#define API_ERROR_CODE_TOO_MANNY_DIGITS 205
#define API_ERROR_CODE_UPDATE_IP_FAILED 206

#endif